export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_REQUEST_PAY_REQUEST = 'ORDER_REQUEST_PAY_REQUEST'
export const ORDER_REQUEST_PAY_SUCCESS = 'ORDER_REQUEST_PAY_SUCCESS'
export const ORDER_REQUEST_PAY_FAIL = 'ORDER_REQUEST_PAY_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_LIST_PAID_REQUEST = 'ORDER_LIST_PAID_REQUEST'
export const ORDER_LIST_PAID_SUCCESS = 'ORDER_LIST_PAID_SUCCESS'
export const ORDER_LIST_PAID_FAIL = 'ORDER_LIST_PAID_FAIL'

export const ORDER_LIST_UNPAID_REQUEST = 'ORDER_LIST_UNPAID_REQUEST'
export const ORDER_LIST_UNPAID_SUCCESS = 'ORDER_LIST_UNPAID_SUCCESS'
export const ORDER_LIST_UNPAID_FAIL = 'ORDER_LIST_UNPAID_FAIL'

export const ORDER_LIST_DELIVERED_REQUEST = 'ORDER_LIST_DELIVERED_REQUEST'
export const ORDER_LIST_DELIVERED_SUCCESS = 'ORDER_LIST_DELIVERED_SUCCESS'
export const ORDER_LIST_DELIVERED_FAIL = 'ORDER_LIST_DELIVERED_FAIL'
