export const POSTAL_GET_PROVINCE_REQUEST = 'POSTAL_GET_PROVINCE_REQUEST'
export const POSTAL_GET_PROVINCE_SUCCESS = 'POSTAL_GET_PROVINCE_SUCCESS'
export const POSTAL_GET_PROVINCE_FAIL = 'POSTAL_GET_PROVINCE_FAIL'

export const POSTAL_GET_CITY_REQUEST = 'POSTAL_GET_CITY_REQUEST'
export const POSTAL_GET_CITY_SUCCESS = 'POSTAL_GET_CITY_SUCCESS'
export const POSTAL_GET_CITY_FAIL = 'POSTAL_GET_CITY_FAIL'

export const POSTAL_GET_SUBDISTRICT_REQUEST = 'POSTAL_GET_SUBDISTRICT_REQUEST'
export const POSTAL_GET_SUBDISTRICT_SUCCESS = 'POSTAL_GET_SUBDISTRICT_SUCCESS'
export const POSTAL_GET_SUBDISTRICT_FAIL = 'POSTAL_GET_SUBDISTRICT_FAIL'
