export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_by_category_REQUEST =
  'PRODUCT_LIST_by_category_REQUEST'
export const PRODUCT_LIST_by_category_SUCCESS =
  'PRODUCT_LIST_by_category_SUCCESS'
export const PRODUCT_LIST_by_category_FAIL = 'PRODUCT_LIST_by_category_FAIL'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const CATEGORY_DETAIL_REQUEST = 'CATEGORY_DETAIL_REQUEST'
export const CATEGORY_DETAIL_SUCCESS = 'CATEGORY_DETAIL_SUCCESS'
export const CATEGORY_DETAIL_FAIL = 'CATEGORY_DETAIL_FAIL'
export const CATEGORY_DETAIL_RESET = 'CATEGORY_DETAIL_RESET'

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'
export const CATEGORY_LIST_RESET = 'CATEGORY_LIST_RESET'

export const CATEGORY_DETAIL_ID_REQUEST = 'CATEGORY_DETAIL_ID_REQUEST'
export const CATEGORY_DETAIL_ID_SUCCESS = 'CATEGORY_DETAIL_ID_SUCCESS'
export const CATEGORY_DETAIL_ID_FAIL = 'CATEGORY_DETAIL_ID_FAIL'
export const CATEGORY_DETAIL_ID_RESET = 'CATEGORY_DETAIL_ID_RESET'
